baseURL = '/'
languageCode = 'en-us'
title = 'My PaperMod Site'
theme = "PaperMod"

[params]
    env = "production"
    title = "My Blog"
    description = "Personal portfolio and blog"
    showShareButtons = true
    showCodeCopyButtons = true